name: generate ASCII Art

on:
  push
jobs:
  readme_job_0:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Welcome message
      run: echo "My frist job"
           ls -ltra
           cat README.md
      
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay Cmd
      run: cowsay -f dragon "run for cover, I am a DRAGON..." >> dragon.txt

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

    - name: Sleep for 30 seconds
      run: sleep 30

    - name: Read file
      run: cat dragon.txt

    - name: List Repo Files
      run: ls -ltra
  
      
